#!/bin/bash
# Tailscale Mesh Setup Script
# ============================
# Hardens and configures your Tailscale mesh for agent operation

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== TAILSCALE MESH SECURITY SETUP ===${NC}"
echo ""

# Check if running as root for some operations
if [ "$EUID" -eq 0 ]; then
   echo -e "${YELLOW}Running as root - will configure system settings${NC}"
   ROOT=true
else
   echo -e "${YELLOW}Not running as root - skipping system config${NC}"
   ROOT=false
fi

# Node identification
NODE_NAME=$(hostname)
echo -e "${GREEN}Configuring node: $NODE_NAME${NC}"

# Apply kernel security settings if root
if [ "$ROOT" = true ]; then
    echo "Applying kernel security settings..."
    cp tailscale-security.conf /etc/sysctl.d/99-tailscale-security.conf
    sysctl --system
    echo -e "${GREEN}✓ Kernel settings applied${NC}"
fi

# Check Tailscale status
echo ""
echo -e "${BLUE}Current Tailscale Status:${NC}"
tailscale status

# Enable Tailscale features
echo ""
echo -e "${BLUE}Enabling Tailscale features...${NC}"

# Enable SSH (for agent communication)
echo "Enabling Tailscale SSH..."
tailscale up --ssh 2>/dev/null || echo "SSH already enabled"

# Enable funnel (for external access if needed)
# echo "Enabling Tailscale Funnel..."
# tailscale up --funnel 2>/dev/null || echo "Funnel status unchanged"

# Configure as subnet router if on primary node
if [ "$NODE_NAME" = "pop-os" ]; then
    echo ""
    echo -e "${YELLOW}Primary node detected (pop-os)${NC}"
    echo "Consider enabling subnet router:"
    echo "  sudo tailscale up --advertise-routes=192.168.0.0/24"
    echo ""
    echo "Consider setting as exit node:"
    echo "  sudo tailscale up --advertise-exit-node"
fi

# Generate SSH config for easy node access
echo ""
echo -e "${BLUE}Generating SSH config...${NC}"

mkdir -p ~/.ssh
cat > ~/.ssh/config.d/tailscale-nodes << 'EOF'
# Tailscale Mesh Nodes
# Auto-generated by setup-tailscale.sh

Host pop-os
    HostName 100.124.152.86
    User gringo
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ~/.ssh/known_hosts.tailscale

Host fyl
    HostName 100.114.102.1
    User lyfer1904
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ~/.ssh/known_hosts.tailscale

Host *-ts
    User gringo
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking accept-new

# Short aliases
Host razor
    HostName 100.124.152.86
    User gringo
    IdentityFile ~/.ssh/id_ed25519

Host kali
    HostName 100.114.102.1
    User lyfer1904
    IdentityFile ~/.ssh/id_ed25519
EOF

# Include in main ssh config if not already
if ! grep -q "Include ~/.ssh/config.d/tailscale-nodes" ~/.ssh/config 2>/dev/null; then
    echo "Include ~/.ssh/config.d/tailscale-nodes" > ~/.ssh/config.tmp
    cat ~/.ssh/config >> ~/.ssh/config.tmp 2>/dev/null || true
    mv ~/.ssh/config.tmp ~/.ssh/config
    chmod 600 ~/.ssh/config
fi

echo -e "${GREEN}✓ SSH config updated${NC}"

# Create host aliases
echo ""
echo -e "${BLUE}Setting up shell aliases...${NC}"

cat >> ~/.bash_aliases << 'EOF'

# Tailscale Mesh Aliases
alias tss='tailscale status'
alias tsu='tailscale up'
alias tsd='tailscale down'
alias ssh-pop='ssh pop-os'
alias ssh-fyl='ssh fyl'
alias ssh-razor='ssh razor'
alias ssh-kali='ssh kali'
EOF

echo -e "${GREEN}✓ Shell aliases added${NC}"

# Generate node status script
cat > ~/bin/mesh-status << 'EOF'
#!/bin/bash
# Quick mesh status check

echo "=== TAILSCALE MESH STATUS ==="
echo ""
tailscale status
echo ""
echo "=== CONNECTIVITY TEST ==="
echo -n "pop-os: "
ping -c 1 -W 2 100.124.152.86 > /dev/null 2>&1 && echo "✓ ONLINE" || echo "✗ OFFLINE"
echo -n "fyl: "
ping -c 1 -W 2 100.114.102.1 > /dev/null 2>&1 && echo "✓ ONLINE" || echo "✗ OFFLINE"
EOF

chmod +x ~/bin/mesh-status 2>/dev/null || chmod +x ~/bin/mesh-status

echo ""
echo -e "${GREEN}=== SETUP COMPLETE ===${NC}"
echo ""
echo "Commands:"
echo "  mesh-status     - Check mesh health"
echo "  ssh pop-os      - SSH to desktop"
echo "  ssh fyl         - SSH to laptop"
echo "  tss             - Tailscale status"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Ensure SSH keys are set up: ssh-copy-id -i ~/.ssh/id_ed25519.pub user@host"
echo "2. Test connectivity: mesh-status"
echo "3. On pop-os: sudo systemctl start razor-master"
